[[getting]]
= Getting Spring LDAP

This section describes how to get the Spring LDAP binaries.
See xref:community.adoc#community-source[Source Code] for how to obtain the source code.

== Release Numbering

Spring LDAP versions are formatted as MAJOR.MINOR.PATCH such that:

* MAJOR versions may contain breaking changes.
Typically, these are done to provide improved security to match modern security practices.
* MINOR versions contain enhancements but are considered passive updates.
* PATCH level should be perfectly compatible, forwards and backwards, with the possible exception of changes that fix bugs.


[[maven]]
== Usage

As most open source projects, Spring LDAP deploys its dependencies as Maven artifacts, which makes them compatible with both Maven and Gradle. The following sections demonstrate how to integrate Spring LDAP with these build tools, with examples for Spring Boot and standalone usage.

[[getting-maven-boot]]
[[getting-gradle-boot]]
=== Spring Boot

Spring Boot provides a `spring-boot-starter-ldap` starter that aggregates Spring LDAP-related dependencies.
The simplest and preferred way to use the starter is to use https://docs.spring.io/initializr/docs/current/reference/html/[Spring Initializr] by using an IDE integration in (https://joshlong.com/jl/blogPost/tech_tip_geting_started_with_spring_boot.html[Eclipse] or https://www.jetbrains.com/help/idea/spring-boot.html#d1489567e2[IntelliJ], https://github.com/AlexFalappa/nb-springboot/wiki/Quick-Tour[NetBeans]) or through https://start.spring.io.
Alternatively, you can manually add the starter, as the following example shows:

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... other dependency elements ... -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-ldap</artifactId>
	</dependency>
</dependencies>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	implementation "org.springframework.boot:spring-boot-starter-ldap"
}
----
======

Since Spring Boot provides a Maven BOM to manage dependency versions, you do not need to specify a version.
If you wish to override the Spring LDAP version, you can do so with a build property as shown below:

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring-ldap.version>{project-version}</spring-ldap.version>
</properties>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring-ldap.version']='{project-version}'
----
======

Since Spring LDAP makes breaking changes only in major releases, you can safely use a newer version of Spring LDAP with Spring Boot.
However, at times, you may need to update the version of Spring Framework as well.
You can do so by adding a build property like so:

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring.version>{spring-core-version}</spring.version>
</properties>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring.version']='{spring-core-version}'
----
======

If you use additional features (such as LDIF), you need to also include the appropriate xref:modules.adoc#modules[modules].

[[getting-maven-no-boot]]
=== Standalone Usage (Without Spring Boot)

When you use Spring LDAP without Spring Boot, you must specify the version you intend to use:.

[tabs]
======
Maven::
+
.pom.xml
[source,xml,ubs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... other dependency elements ... -->
		<dependency>
			<groupId>org.springframework.ldap</groupId>
			<artifactId>spring-ldap-core</artifactId>
			<version>{project-version}</version>
		</dependency>
	</dependencies>
</dependencyManagement>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.ldap:spring-ldap-core:{project-version}'
	}
}
----
======

[TIP]
Spring provides a https://github.com/spring-gradle-plugins/dependency-management-plugin[`Dependency Management Plugin`] for Gradle

For most projects, including `spring-ldap-core` is sufficient.

If you use additional features (such as LDIF), you need to also include the appropriate xref:modules.adoc#modules[modules].

Spring LDAP builds against Spring Framework 6 but should generally work with any newer version of Spring Framework 5.x.
Many users are likely to run afoul of the fact that Spring LDAP's transitive dependencies resolve Spring Framework 6, which can cause strange classpath problems.
The easiest way to resolve this is to use the `spring-framework-bom` within the `<dependencyManagement>` section of your `pom.xml` or your `dependencyManagement` section of your `build.gradle`.

[tabs]
======
Maven::
+
.pom.xml
[source,xml,subs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... other dependency elements ... -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-framework-bom</artifactId>
			<version>{spring-core-version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
----

Gradle::
+
.build.gradle
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework:spring-framework-bom:{spring-core-version}'
	}
}
----
======

[TIP]
Spring provides a https://github.com/spring-gradle-plugins/dependency-management-plugin[`Dependency Management Plugin`] for Gradle

The preceding example ensures that all the transitive dependencies of Spring LDAP use the Spring 6 modules.

[NOTE]
====
This approach uses Maven's "`bill of materials`" (BOM) concept and is only available in Maven 2.0.9+.
For additional details about how dependencies are resolved, see https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven's Introduction to the Dependency Mechanism documentation].
====

[[maven-repositories]]
=== Maven Repositories
All https://github.com/spring-projects/spring-security/wiki/Release-Schedule-Guidelines[GA releases] are deployed to Maven Central, so you need not declare additional Maven repositories in your build configuration.

For Gradle using the `mavenCentral()` repository is sufficient for GA releases.

.build.gradle
[source,groovy]
----
repositories {
	mavenCentral()
}
----

If you use a SNAPSHOT version, you need to ensure that you have the Spring Snapshot repository defined:

[tabs]
======
Maven::
+
.pom.xml
[source,xml]
----
<repositories>
	<!-- ... possibly other repository elements ... -->
	<repository>
		<id>spring-snapshot</id>
		<name>Spring Snapshot Repository</name>
		<url>https://repo.spring.io/snapshot</url>
	</repository>
</repositories>
----

Gradle::
+
.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/snapshot' }
}
----
======

If you use a milestone or release candidate version, you need to ensure that you have the Spring Milestone repository defined, as the following example shows:

[tabs]
======
Maven::
+
.pom.xml
[source,xml]
----
<repositories>
	<!-- ... possibly other repository elements ... -->
	<repository>
		<id>spring-milestone</id>
		<name>Spring Milestone Repository</name>
		<url>https://repo.spring.io/milestone</url>
	</repository>
</repositories>
----

Gradle::
+
.build.gradle
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/milestone' }
}
----
======

