[[introduction]]
= Introduction

This section offers a relatively quick introduction to Spring LDAP. It includes the following content:

* xref:introduction.adoc#spring-ldap-introduction-overview[Overview]
* xref:introduction.adoc#spring-ldap-traditional-ldap-vs-ldaptemplate[Traditional Java LDAP versus `LdapClient`]
* xref:introduction.adoc#spring-ldap-packaging-overview[Packaging Overview]
* xref:introduction.adoc#spring-ldap-getting-started[Getting Started]
* xref:introduction.adoc#spring-ldap-support[Support]
* xref:introduction.adoc#spring-ldap-acknowledgements[Acknowledgements]

[[spring-ldap-introduction-overview]]
== Overview
Spring LDAP is designed to simplify LDAP programming in Java. Some of the features provided by the library are:

* https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html[`JdbcTemplate`]-style template simplifications to LDAP programming.
* JPA- or Hibernate-style annotation-based object and directory mapping.
* Spring Data repository support, including support for QueryDSL.
* Utilities to simplify building LDAP queries and distinguished names.
* Proper LDAP connection pooling.
* Client-side LDAP compensating transaction support.

[[spring-ldap-traditional-ldap-vs-ldapclient]]
[[spring-ldap-traditional-ldap-vs-ldaptemplate]]
== Traditional Java LDAP versus `LdapClient`

Consider a method that should search some storage for all persons and return their names in a list.
By using JDBC, we would create a _connection_ and run a _query_ by using a _statement_. We would then loop over the _result set_ and retrieve the _column_ we want, adding it to a list.

Working against an LDAP database with JNDI, we would create a _context_ and perform a _search_ by using a _search filter_. We would then loop over the resulting _naming enumeration_, retrieve the _attribute_ we want, and add it to a list.

The traditional way of implementing this person-name search method in Java LDAP looks like the next example. Note the code marked *bold* - this is the code that
actually performs tasks related to the business purpose of the method. The rest is plumbing.

====
[source,java]
[subs="verbatim,quotes"]
----
package com.example.repository;

public class TraditionalPersonRepoImpl implements PersonRepo {
   public List<String> getAllPersonNames() {
      Hashtable env = new Hashtable();
      env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");
      env.put(Context.PROVIDER_URL, "ldap://localhost:389/dc=example,dc=com");

      DirContext ctx;
      try {
         ctx = new InitialDirContext(env);
      } catch (NamingException e) {
         throw new RuntimeException(e);
      }

      List<String> list = new LinkedList<String>();
      NamingEnumeration results = null;
      try {
         SearchControls controls = new SearchControls();
         controls.setSearchScope(SearchControls.SUBTREE_SCOPE);
         results = ctx.**search**("", **"(objectclass=person)"**, controls);

         while (results.hasMore()) {
            SearchResult searchResult = (SearchResult) results.next();
            Attributes attributes = searchResult.getAttributes();
            **Attribute attr = attributes.get("cn");
            String cn = attr.get().toString();**
            list.add(cn);
         }
      } catch (NameNotFoundException e) {
         // The base context was not found.
         // Just clean up and exit.
      } catch (NamingException e) {
         throw new RuntimeException(e);
      } finally {
         if (results != null) {
            try {
               results.close();
            } catch (Exception e) {
               // Never mind this.
            }
         }
         if (ctx != null) {
            try {
               ctx.close();
            } catch (Exception e) {
               // Never mind this.
            }
         }
      }
      **return list;**
   }
}
----
====

By using the Spring LDAP `AttributesMapper` and `LdapClient` classes, we get the exact same functionality with the following code:

====
[source,java]
[subs="verbatim,quotes"]
----
package com.example.repo;
import static org.springframework.ldap.query.LdapQueryBuilder.query;

public class PersonRepoImpl implements PersonRepo {
   private LdapClient ldapClient;

   public void setLdapClient(LdapClient ldapClient) {
      this.ldapClient = ldapClient;
   }

   public List<String> getAllPersonNames() {
      return ldapClient.search().query(
            **query().where("objectclass").is("person")**
         ).map((Attributes attrs) ->
            **attrs.get("cn").get().toString()**
         ).list();
   }
}
----
====

The amount of boilerplate code is significantly less than in the traditional example.
The `LdapClient` search method makes sure a `DirContext` instance is created, performs the search, maps the attributes to a string by using the given `AttributesMapper`,
collects the strings in an internal list, and, finally, returns the list. It also makes sure that the `NamingEnumeration` and `DirContext` are properly closed and
takes care of any exceptions that might happen.

Naturally, this being a Spring Framework sub-project, we use Spring to configure our application, as follows:

====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:ldap="http://www.springframework.org/schema/ldap"
       xsi:schemaLocation="http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/ldap https://www.springframework.org/schema/ldap/spring-ldap.xsd">

   <ldap:context-source
          url="ldap://localhost:389"
          base="dc=example,dc=com"
          username="cn=Manager"
          password="secret" />

   <bean id="ldapClient" class="org.springframework.ldap.core.LdapClient" factory-method="create">
        <constructor-arg ref="contextSource" />
    </bean>

   <bean id="personRepo" class="com.example.repo.PersonRepoImpl">
      <property name="ldapClient" ref="ldapClient" />
   </bean>
</beans>
----
====

NOTE: To use the custom XML namespace to configure the Spring LDAP components, you need to include references to this namespace in your XML declaration, as in the preceding example.

[[spring-ldap-packaging-overview]]
== Packaging Overview

At a minimum, to use Spring LDAP you need the following:

* `spring-ldap-core`: The Spring LDAP library
* `spring-core`: Miscellaneous utility classes used internally by the framework
* `spring-beans`: Interfaces and classes for manipulating Java beans
* `slf4j`: A simple logging facade, used internally

In addition to the required dependencies, the following optional dependencies are required for certain functionality:

* `spring-data-ldap`: Base infrastructure for repository support and so on
* `spring-context`: Needed if your application is wired up by using the Spring Application Context. `spring-context` adds the ability for application objects to obtain resources by using a consistent API. It is definitely needed if you plan to use the `BaseLdapPathBeanPostProcessor`.
* `spring-tx`: Needed if you plan to use the client-side compensating transaction support.
* `spring-jdbc`: Needed if you plan to use the client-side compensating transaction support.
* `commons-pool`: Needed if you plan to use the pooling functionality.
* `spring-batch`: Needed if you plan to use the LDIF parsing functionality together with Spring Batch.

NOTE: `spring-data-ldap` transitively adds `spring-repository.xsd`, which `spring-ldap.xsd` uses.
Because of this, Spring LDAP's XML config support requires the dependency even when Spring Data's feature set is not in use.

[[spring-ldap-getting-started]]
== Getting Started

The https://github.com/spring-projects/spring-ldap/tree/main/samples[samples] provide some useful examples of how to use Spring LDAP for common use cases.

[[spring-ldap-support]]
== Support

If you have questions, ask them on https://stackoverflow.com/questions/tagged/spring-ldap[Stack Overflow with the `spring-ldap` tag].
The project web page is https://spring.io/spring-ldap/.

[[spring-ldap-acknowledgements]]
== Acknowledgements

The initial effort when starting the Spring LDAP project was sponsored by https://www.jayway.com[Jayway].
Current maintenance of the project is funded by https://pivotal.io[Pivotal], which has since been acquired by https://vmware.com[VMware].

Thanks to https://structure101.com/[Structure101] for providing an open source license that has come in handy for keeping the project structure in check.

