[[testing]]
= Testing

This section covers testing with Spring LDAP. It contains the following topics:

* xref:testing.adoc#spring-ldap-testing-embedded-server[Using an Embedded Server]
* xref:testing.adoc#spring-ldap-testing-apacheds[ApacheDS]
* xref:testing.adoc#spring-ldap-testing-unboundid[UnboundID]

[[spring-ldap-testing-embedded-server]]
== Using an Embedded Server

`spring-ldap-test` supplies an embedded LDAP server that is based on https://directory.apache.org/apacheds/[ApacheDS] or https://www.ldap.com/unboundid-ldap-sdk-for-java[UnboundID].

NOTE: `spring-ldap-test` is compatible with ApacheDS 1.5.5. Newer versions of ApacheDS are not supported.

To get started, you need to include the `spring-ldap-test` dependency.

The following listing shows how to include the `spring-ldap-test` for Maven:

[source,xml,subs="+attributes"]
----
<dependency>
    <groupId>org.springframework.ldap</groupId>
    <artifactId>spring-ldap-test</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

The following listing shows how to include the `spring-ldap-test` for Gradle:

[source,groovy]
[subs="verbatim,quotes,attributes"]
----
testCompile "org.springframework.ldap:spring-ldap-test:{project-version}"
----

[[spring-ldap-testing-apacheds]]
== ApacheDS

To use ApacheDS, you need to include a number of ApacheDS dependencies.

The following example shows how to include the ApacheDS dependencies for Maven:

[source,xml,subs="verbatim,quotes,attributes"]
----
<dependencies>
    <dependency>
        <groupId>org.apache.directory.server</groupId>
        <artifactId>apacheds-core</artifactId>
        <version>{apacheds-core-version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.directory.server</groupId>
        <artifactId>apacheds-core-entry</artifactId>
        <version>{apacheds-core-entry-version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.directory.server</groupId>
        <artifactId>apacheds-protocol-shared</artifactId>
        <version>{apacheds-protocol-shared-version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.directory.server</groupId>
        <artifactId>apacheds-protocol-ldap</artifactId>
        <version>{apacheds-protocol-ldap-version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.directory.server</groupId>
        <artifactId>apacheds-server-jndi</artifactId>
        <version>{apacheds-server-jndi-version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.directory.shared</groupId>
        <artifactId>shared-ldap</artifactId>
        <version>{shared-ldap-version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----

The following example shows how to include the ApacheDS dependencies for Gradle:

[source,groovy,subs="verbatim,quotes,attributes"]
----
dependencies {
    testImplementation "org.apache.directory.server:apacheds-core:{apacheds-core-version}"
    testImplementation "org.apache.directory.server:apacheds-core-entry:{apacheds-core-entry-version}"
    testImplementation "org.apache.directory.server:apacheds-protocol-shared:{apacheds-protocol-shared-version}"
    testImplementation "org.apache.directory.server:apacheds-protocol-ldap:{apacheds-protocol-ldap-version}"
    testImplementation "org.apache.directory.server:apacheds-server-jndi:{apacheds-server-jndi-version}"
    testImplementation "org.apache.directory.shared:shared-ldap:{shared-ldap-version}"
}
----

The following bean definition creates an embedded LDAP server:

[source,xml]
----
<bean id="embeddedLdapServer" class="org.springframework.ldap.test.EmbeddedLdapServerFactoryBean">
    <property name="partitionName" value="example"/>
    <property name="partitionSuffix" value="dc=261consulting,dc=com" />
    <property name="port" value="9321" />
</bean>
----

`spring-ldap-test` provides a mechanism to populate the LDAP server by using `org.springframework.ldap.test.LdifPopulator`. To use it, create a bean similar to the following:

[source,xml]
----
<bean class="org.springframework.ldap.test.LdifPopulator" depends-on="embeddedLdapServer">
    <property name="contextSource" ref="contextSource" />
    <property name="resource" value="classpath:/setup_data.ldif" />
    <property name="base" value="dc=jayway,dc=se" />
    <property name="clean" value="true" />
    <property name="defaultBase" value="dc=jayway,dc=se" />
</bean>
----

Another way to work against an embedded LDAP server is by using `org.springframework.ldap.test.TestContextSourceFactoryBean`, as follows:

[source,xml]
----
<bean id="contextSource" class="org.springframework.ldap.test.TestContextSourceFactoryBean">
    <property name="defaultPartitionSuffix" value="dc=jayway,dc=se" />
    <property name="defaultPartitionName" value="jayway" />
    <property name="principal" value="uid=admin,ou=system" />
    <property name="password" value="secret" />
    <property name="ldifFile" value="classpath:/setup_data.ldif" />
    <property name="port" value="1888" />
</bean>
----

Also, `org.springframework.ldap.test.LdapTestUtils` provides methods to programmatically work with an embedded LDAP server.

[[spring-ldap-testing-unboundid]]
== UnboundID

To use UnboundID, you need to include an UnboundID dependency.

The following example shows how to include the UnboundID dependency for Maven:

[source,xml,subs="verbatim,quotes,attributes"]
----
<dependency>
    <groupId>com.unboundid</groupId>
    <artifactId>unboundid-ldapsdk</artifactId>
    <version>{unboundid-ldapsdk-version}</version>
    <scope>test</scope>
</dependency>
----

The following example shows how to include the UnboundID dependency for Gradle:

[source,groovy,subs="verbatim,quotes,attributes"]
----
testCompile "com.unboundid:unboundid-ldapsdk:{unboundid-ldapsdk-version}"
----

The following bean definition creates an embedded LDAP server:

[source,java]
----
@Bean
EmbeddedLdapServer embeddedLdapServer() {
    return EmbeddedLdapServer.withPartitionSuffix("dc=jayway,dc=se")
        .partitionName("jayway")
        .port(18881)
        .configurationCustomizer((config) -> config.setCodeLogDetails(tempLogFile, true))
        .build();
}
----

Alternatively, you can use the `org.springframework.ldap.test.unboundid.LdifPopulator` to create and populate the LDAP server. To use it, create a bean similar to the following:

[source,xml]
----
<bean class="org.springframework.ldap.test.unboundid.LdifPopulator" depends-on="embeddedLdapServer">
    <property name="contextSource" ref="contextSource" />
    <property name="resource" value="classpath:/setup_data.ldif" />
    <property name="base" value="dc=jayway,dc=se" />
    <property name="clean" value="true" />
    <property name="defaultBase" value="dc=jayway,dc=se" />
</bean>
----

Another way to work against an embedded LDAP server is by using `org.springframework.ldap.test.unboundid.TestContextSourceFactoryBean`.
To use it, create a bean similar to the following:

[source,xml]
----
<bean id="contextSource" class="org.springframework.ldap.test.unboundid.TestContextSourceFactoryBean">
    <property name="defaultPartitionSuffix" value="dc=jayway,dc=se" />
    <property name="defaultPartitionName" value="jayway" />
    <property name="principal" value="uid=admin,ou=system" />
    <property name="password" value="secret" />
    <property name="ldifFile" value="classpath:/setup_data.ldif" />
    <property name="port" value="1888" />
</bean>
----

Also, `org.springframework.ldap.test.unboundid.LdapTestUtils` provide methods to programmatically work with an embedded LDAP server.
