name: Deploy Schema
description: Deploys the schema zip to the docs site

inputs:
  java-version:
    description: "The Java version to use"
    required: false
    default: "17"

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: spring-io/spring-gradle-build-action@c8668747d7c264864c8c7f7026d0d277d14a78dc  # v2.0.6
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
    - name: Deploy Schema
      shell: bash
      run: |
        ./gradlew deploySchema -PdeployDocsSshKey="$DOCS_SSH_KEY" -PdeployDocsSshUsername="$DOCS_USERNAME" -PdeployDocsHost="$DOCS_HOST" --stacktrace --info
