name: Deploy Schema

on:
  workflow_call:
    inputs:
      java-version:
        description: Java version to build the schema with
        type: string
        default: '25'
      runner:
        description: Runner to deploy on
        type: string
        default: ubuntu-latest

jobs:
  deploy-schema:
    name: Deploy Schema
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Deploy Schema
        uses: ./.github/actions/deploy-schema
        with:
          java-version: ${{ inputs.java-version }}
        env:
          DOCS_SSH_KEY: ${{ secrets.DOCS_SSH_KEY }}
          DOCS_USERNAME: ${{ secrets.DOCS_USERNAME }}
          DOCS_HOST: ${{ secrets.DOCS_HOST }}
