name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - '*.x'
      - 'docs-build'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@2ec214c1531a20b72fd8b175f67e2e0d7256fc90
    with:
      mergeArguments: --auto --rebase