name: Dependabot - Build Pull Request

on: pull_request

permissions:
  contents: read

env:
  JAVA_VERSION: '17'
  ORG_GRADLE_PROJECT_artifactoryUsername: ${{ vars.INTERNAL_CI && secrets.ARTIFACTORY_RO_USERNAME }}
  ORG_GRADLE_PROJECT_artifactoryPassword: ${{ vars.INTERNAL_CI && secrets.ARTIFACTORY_RO_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ${{ vars.INTERNAL_CI && 'ubuntu22-2-8' || 'ubuntu-latest' }}
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: spring-io/spring-security-actions/pr-build@96df48300f5fa058d0765832d48a534cc6a378d5 # 0.0.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
  build-check:
    name: Build
    needs: build
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
