name: Pull Request - Build

on: pull_request

permissions:
  contents: read

env:
  JAVA_VERSION: '25'
  ORG_GRADLE_PROJECT_artifactoryUsername: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
  ORG_GRADLE_PROJECT_artifactoryPassword: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu22-2-8
    if: github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: spring-io/spring-security-actions/pr-build@7b123d42b18f8e52c1925c5eecc3e217bfe3b31b  # 0.0.2
        with:
          java-version: ${{ env.JAVA_VERSION }}
  build-check:
    name: Build
    needs: build
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
