name: Pull Request - Build

on: pull_request

permissions:
  contents: read

env:
  JAVA_VERSION: '17'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.repository == 'spring-projects/spring-ldap'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: spring-io/spring-security-actions/pr-build@15a5e9ef75eee29c39237c6821939a04e43a4b11  # main
        with:
          java-version: ${{ env.JAVA_VERSION }}
  build-check:
    name: Build
    needs: build
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
