name: Pull Request - Build

on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.repository == 'spring-projects/spring-ldap'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: spring-io/spring-security-actions/pr-build@4386090bf7852faa1d61782f981811441757dbb8  # main
        with:
          java-version: '17'
