name: Update spring-security-release-tools

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 06:00 UTC

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: spring-io/spring-security-release-tools/update-bot@491486cb49b06ccaefe7e9220ed5f7b81d89ce40 # main
