name: Update spring-security-release-tools

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 06:00 UTC

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      - uses: spring-io/spring-security-release-tools/update-bot@bdf695aa698da0eb03913457abbf8da98e9523b6 # 1.0.x
        with:
          token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
